name: Renew Exchange Connection String

on:
  workflow_dispatch:
    inputs:
      appid:
        description: "Id of the Azure AD application"
        required: true
        default: "d7e7315a-17fc-444e-bb8b-c299a5f66fc5"
      organisation:
        description: "organisation"
        required: true
        default: "CHRISTIANIABPOS.onmicrosoft.com"
      domain:
        description: "Domain"
        required: true
        default: "79dc228f-c8f2-4016-8bf0-b990b6c72e98"

      ownerupn:
        description: "Owner UPN of the Azure AD application"
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      # Define environment variables here
      WORKDIR: ${{ github.workspace }}
      TARGET_APPID: ${{github.event.inputs.environment }}
      TARGET_ORGANISATION: ${{github.event.inputs.organisation }}
      TARGET_DOMAIN: ${{github.event.inputs.domain }}
      OWNERUPN: ${{github.event.inputs.ownerupn }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     allow-no-subscriptions: true
      #     enable-AzPSSession: true

      - name: Update Metadata
        run: pwsh ./renew-exchange-connectionstring/run.ps1
        shell: pwsh
