name: Renew Exchange Connection String

on:
  workflow_dispatch:
    inputs:
      appid:
        description: "Id of the Azure AD application"
        required: true

      ownerupn:
        description: "Owner UPN of the Azure AD application"
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      # Define environment variables here
      WORKDIR: ${{ github.workspace }}
      APPID: ${{github.event.inputs.environment }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Metadata
        run: pwsh ./renew-exchange-connectionstring/run.ps1
        shell: pwsh
